apiVersion: v1
clusters:
- cluster:
    certificate-authority: /var/jenkins_home/minikube/ca.crt
    server: https://192.168.49.2:8443   # Minikube container IP
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /var/jenkins_home/minikube/client.crt
    client-key: /var/jenkins_home/minikube/client.key

